### Mathematical Fucntions in Series and Indexing in Series

In [2]:
import numpy as np
import pandas as pd

In [3]:
path = r"D:\pythonProjectGenAI\Learn_GENAI\GENAI\DataSets\youtube_dataset\youtube_channel_info_v1.csv"

In [4]:
df = pd.read_csv(path)

df.head()

,channel_name,channel_id,view_count,category,country,defaultLanguage,subscriber_count,created_date,description,custom_url,thumbnail,video_count
0,BLACKPINK,UCOmHUn--16B90oW2L6FRR3A,39962585446,"Music of Asia, Pop music, Music, Electronic music",KR,NaN,99000000,2016-06-29T03:15:23Z,BLACKPINK Official YouTube Channel 블랙핑크 공식 유튜브...,@blackpink,https://yt3.ggpht.com/U3VrCkKjzTpQ3VYv4SCPjNfD...,636
1,HYBE LABELS,UC3IZKseVpdzPSBaWxBxundA,41604896923,"Hip hop music, Pop music, Music, Music of Asia",KR,NaN,78700000,2008-06-04T08:23:22Z,Welcome to the official YouTube channel of HYB...,@hybelabels,https://yt3.ggpht.com/ytc/AIdro_l8g0yRFG8xoe_q...,2817
2,BILLIE EILISH,UCVNE660NcgYzi18LwwUZb7Q,14316364,NaN,NaN,NaN,82300,2019-01-18T05:14:32Z,NaN,@billieeilish8477,https://yt3.ggpht.com/ytc/AIdro_n3NfvUAVtcUJvW...,1
3,Shemaroo,UCF1JIbMUs6uqoZEY1Haw0GQ,27011004224,"Entertainment, Film",IN,NaN,60400000,2007-09-01T11:44:51Z,"Welcome to ShemarooEnt, one of the finest dest...",@shemaroo,https://yt3.ggpht.com/ytc/AIdro_mhdF4RNZM9OHP-...,13374
4,JuegaGerman,UCYiGq8XF7YQD00x7wAd62Zg,17573028501,"Role-playing video game, Action game, Video ga...",CL,NaN,54200000,2013-05-19T00:09:13Z,Lento pero seguro.,@juegagerman,https://yt3.ggpht.com/vOsrLzWD4z1dbr470nEXydi3...,2368

In [5]:
subs = df['subscriber_count']
subs

0        99000000
1        78700000
2           82300
3        60400000
4        54200000
           ...
15825      241000
15826     4260000
15827     2920000
15828     3250000
15829     2880000
Name: subscriber_count, Length: 15830, dtype: int64

In [6]:
#mathematical functions
# 1. sum() -> sum of all values present in series
subs.sum()

np.int64(63632278000)

In [8]:
# 2. product() -> product of all values present in series 
subs.product()

np.int64(0)

In [10]:
subs.sort_values()

12123        50000
6004         50000
11026        50000
13557        50000
11469        50100
           ...
23       146000000
10       187000000
32       198000000
10447    305000000
7        443000000
Name: subscriber_count, Length: 15830, dtype: int64

In [12]:
df.head()

,channel_name,channel_id,view_count,category,country,defaultLanguage,subscriber_count,created_date,description,custom_url,thumbnail,video_count
0,BLACKPINK,UCOmHUn--16B90oW2L6FRR3A,39962585446,"Music of Asia, Pop music, Music, Electronic music",KR,NaN,99000000,2016-06-29T03:15:23Z,BLACKPINK Official YouTube Channel 블랙핑크 공식 유튜브...,@blackpink,https://yt3.ggpht.com/U3VrCkKjzTpQ3VYv4SCPjNfD...,636
1,HYBE LABELS,UC3IZKseVpdzPSBaWxBxundA,41604896923,"Hip hop music, Pop music, Music, Music of Asia",KR,NaN,78700000,2008-06-04T08:23:22Z,Welcome to the official YouTube channel of HYB...,@hybelabels,https://yt3.ggpht.com/ytc/AIdro_l8g0yRFG8xoe_q...,2817
2,BILLIE EILISH,UCVNE660NcgYzi18LwwUZb7Q,14316364,NaN,NaN,NaN,82300,2019-01-18T05:14:32Z,NaN,@billieeilish8477,https://yt3.ggpht.com/ytc/AIdro_n3NfvUAVtcUJvW...,1
3,Shemaroo,UCF1JIbMUs6uqoZEY1Haw0GQ,27011004224,"Entertainment, Film",IN,NaN,60400000,2007-09-01T11:44:51Z,"Welcome to ShemarooEnt, one of the finest dest...",@shemaroo,https://yt3.ggpht.com/ytc/AIdro_mhdF4RNZM9OHP-...,13374
4,JuegaGerman,UCYiGq8XF7YQD00x7wAd62Zg,17573028501,"Role-playing video game, Action game, Video ga...",CL,NaN,54200000,2013-05-19T00:09:13Z,Lento pero seguro.,@juegagerman,https://yt3.ggpht.com/vOsrLzWD4z1dbr470nEXydi3...,2368

In [13]:
# 3. mean() -> avg of the series or dataset column
subs.mean()

np.float64(4019726.9740998107)

In [14]:
# 4. Meadian() -> sort the series in asending order the middle one is meadian, used when there is genrally outliers like in salary some have 7-10lpa and some few have 40-50lpa but it will increase the mean(avg) so use meadian 
subs.median()

np.float64(1570000.0)

In [15]:
# 5. Mode() -> which value getting repeated maximum times 
subs.mode()

0    1010000
Name: subscriber_count, dtype: int64

In [17]:
country = df['country']
country

0         KR
1         KR
2        NaN
3         IN
4         CL
        ...
15825     IN
15826     HK
15827     US
15828     GB
15829     IN
Name: country, Length: 15830, dtype: str

In [30]:
count=0
for i in country:
    if i == 'US':
        count=count+1
print(count)

4926

In [31]:
country.mode()

0    US
Name: country, dtype: str

In [32]:
country.value_counts()

country
US    4926
IN    2320
GB    1670
CA    1173
AU     965
      ...
UG       1
OM       1
HN       1
ME       1
UM       1
Name: count, Length: 110, dtype: int64

In [33]:
#6. std() -> if i need to get the idea that how the values inside the series sre distrubuted from the average or mean vale then we cancome up with the standard deviation
# salary -> 7,8,6,6.5,7.5   all are near to the 7  ( mean/avg) so -> low std
# salary -> 7,15,4,20,28,17 high std bcz from the mean/avg the values are high and low not nearby
subs.std()

np.float64(8937193.096528104)

In [34]:
# 7. variance -> it also provides the insight about the distribution of data from the mean vale and variance is the square of std
# standard_deviation = |mean - v_1| + |mean - v_2|....../ total count of vales
# variance = std**2
subs.var()

np.float64(79873420444629.6)

In [35]:
# min() & max()
subs.min()

np.int64(50000)

In [36]:
subs.max()

np.int64(443000000)

In [ ]:
# 9. describe() -> it provides the idea of the summary of important mathematical calculations for the data
df.describe()
# 25% -> 25% OF THE VALUES OUT OF MY ALL VALUES ARE LESS THAN THIS VALUE

         view_count  subscriber_count    video_count
count  1.583000e+04      1.583000e+04   15830.000000
mean   1.965941e+09      4.019727e+06    5464.338787
std    6.149327e+09      8.937193e+06   28916.176923
min    0.000000e+00      5.000000e+04       0.000000
25%    1.032884e+08      4.880000e+05     152.000000
50%    4.080212e+08      1.570000e+06     589.000000
75%    1.641828e+09      4.300000e+06    1874.750000
max    3.148151e+11      4.430000e+08  646139.000000

In [39]:
country.describe()

count     14030
unique      110
top          US
freq       4926
Name: country, dtype: object

In [42]:
# Indexing in Series
# 1. posistive indexing
#2. NO negative indexing
# 3. slicing [start:end:skip]
print(subs[7:18])
print(subs[10:21:2])

7     443000000
8      70200000
9      76300000
10    187000000
11     67700000
12     81300000
13     68300000
14     58500000
15     95100000
16     97600000
17     56500000
Name: subscriber_count, dtype: int64
10    187000000
12     81300000
14     58500000
16     97600000
18     81000000
20     58100000
Name: subscriber_count, dtype: int64

In [43]:
# reverse values in series
subs[::-1]

15829     2880000
15828     3250000
15827     2920000
15826     4260000
15825      241000
           ...
4        54200000
3        60400000
2           82300
1        78700000
0        99000000
Name: subscriber_count, Length: 15830, dtype: int64

In [ ]:
# fancy indexing